name: Run Command

on:
  push:
  pull_request:
  workflow_dispatch:
      inputs:
        cmd:
          type: string

jobs:
  runcmd:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ${{ inputs.cmd }}
      - run: ${{ toJSON(env) }}
